### ISSUE TITLE
Chore: Add Build CI for SonarQube

### ISSUE THREAD

**Issue by Mino03947** [Compairifuel/Compairifuel#116]
### Feature Description

To improve the Quality of our code, this can implement to include SonarQube. As an addition to our current **CI**. SonarQube is available on a free plan.

### UI/UX Design (if applicable)

Workflow Code:
```yml
name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      # The analysis requires to retrieve dependencies and build successfully
      - name: Build
        run: <mark><commands_to_build_your_project></mark>
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

Add `sonar-project.properties` in the root of the repository:
```properties
sonar.projectKey=Compairifuel_Compairifuel
sonar.organization=compairifuel


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=Compairifuel
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
```
